<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>io.redback</groupId>
  <artifactId>trial</artifactId>
  <version>0.0.1-SNAPSHOT</version>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<io.firebus.version>2.0.0</io.firebus.version>
		<io.redback.version>2.0.0</io.redback.version>		
	</properties>
	<dependencies>
		<dependency>
			<groupId>io.redback</groupId>
			<artifactId>redback-core</artifactId>
			<version>${io.redback.version}</version>
		</dependency>
		<dependency>
			<groupId>io.firebus</groupId>
			<artifactId>firebus-adapters</artifactId>
			<version>${io.firebus.version}</version>
		</dependency>
		<dependency>
			<groupId>io.firebus</groupId>
			<artifactId>firebus-http</artifactId>
			<version>${io.firebus.version}</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>11</source>
					<target>11</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<configuration>
					<archive>
						<manifest>
							<mainClass>io.redback.RedbackServer</mainClass>
						</manifest>
					</archive>
					<descriptors>
						<descriptor>assembly.xml</descriptor>
					</descriptors>
					<finalName>trial</finalName>
					<outputDirectory>target</outputDirectory>
					<appendAssemblyId>false</appendAssemblyId>
				</configuration>
				<executions>
					<execution>
						<id>make-assembly</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>  
</project>